### ISSUE TITLE
T12 Color theme

### ISSUE THREAD

**Issue by jakub-stejskal** [Voice-from-Fire/vffweb#15]
The application now uses the default MUI color theme (blue).

Goal
Try to experiment with different colors; to better match the logo or to create a more welcoming atmosphere. The default color has a “too technical” feeling for me.

Docs:
https://mui.com/material-ui/customization/theming/
Theme generator:
https://zenoo.github.io/mui-theme-creator/

**Comment by Kobzol** [comment]
Resolved by https://github.com/Voice-from-Fire/vffweb/pull/40.
